pre-commit:
  parallel: true
  commands:
    lint:
      run: bun run lint
      stage_fixed: true
    format:
      run: bun run format
      stage_fixed: true
    type-check:
      run: bun run type-check
      stage_fixed: true

pre-push:
  parallel: true
  commands:
    test:
      run: bun run test
      tags: frontend backend

